channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.0.1
- pip:
  - mlflow==2.21.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - tensorflow-intel==2.16.1
  - tensorflow==2.16.1
name: mlflow-env
