channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.0.1
- pip:
  - mlflow==2.21.2
  - attrs==25.1.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - dill==0.3.8
  - huggingface-hub==0.29.3
  - ipython==8.32.0
  - matplotlib==3.10.0
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - tensorflow-intel==2.16.1
name: mlflow-env
